services:
  hunngaupejakt:
    image: ghcr.io/ninanor/hunngaupejakt:latest
    ports:
      - "3839:3838"
    environment:
      - TZ=Europe/Oslo
      - SHINY_HOST=0.0.0.0
      - SHINY_PORT=3838
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 60s
